services:
  - type: web
    name: telegram-robotic-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TOKEN
        value: توکن_ربات_که_از_BotFather_گرفتی
